### ISSUE TITLE
Error: No transports available

### ISSUE THREAD

**Issue by henrikrudstrom** [eblanshey/safe-api#1]
Hi, nice project.
I tried to run a little test script from the commandline:
´´´
var safe_api = require('safe-api')
safe_api.setup({ firebaseApp: 'intense-torch-2025' })
´´´
but i get an error somewhere:
´´´
Error: No transports available
    at Error (native)
    at Dh (C:\Users\henrud\Documents\SAFE\safe-api-test\node_modules\safe-api\lib\index.js:16920:645)
    at Fh (C:\Users\henrud\Documents\SAFE\safe-api-test\node_modules\safe-api\lib\index.js:16921:23)
    at new Eh (C:\Users\henrud\Documents\SAFE\safe-api-test\node_modules\safe-api\lib\index.js:16920:881)
    at bi (C:\Users\henrud\Documents\SAFE\safe-api-test\node_modules\safe-api\lib\index.js:16940:230)
    at null._onTimeout (C:\Users\henrud\Documents\SAFE\safe-api-test\node_modules\safe-api\lib\index.js:16938:147)
    at Timer.listOnTimeout (timers.js:119:15)
´´´
Any ideas? 
and btw how do i build your project so it doesnt minimize the code?

**Comment by eblanshey** [comment]
Doing a little digging it seems it's because it found no way to connect to Firebase. The `setup()` function initializes the connection. In other words, it wasn't supported from the command line environment you were using. I suggest you try again in a modern browser.

As for minimizing, the [compiled file](https://github.com/eblanshey/safe-api/blob/master/lib/index.js) is not minimized, so it ultimately depends on the settings of your build tool.

Good luck!

**Comment by eblanshey** [comment]
Hey, did you try it in a browser? Hopefully this isn't an issue for you anymore. Let me know otherwise!
